paths:
  logs: 'logs/gold_predictor.log'
  predictions: 'output/predictions.csv'
  plots: 'output/plots/'

symbols:
  gold: 'GC=F'
  related_assets:
    Silver: 'SI=F'
    Oil: 'CL=F'
    SP500: '^GSPC'

lookback_days: 30
train_test_split: 0.8

feature_selection:
  n_features: 30

model_names:
  - 'rf'
  - 'xgb'
  - 'lgbm'
  - 'elasticnet'

lstm:
  units: 64
  dropout: 0.2
  dense_units: 32
  learning_rate: 0.001
  epochs: 100
  batch_size: 32

prediction_interval_confidence: 0.95

anomaly_detection:
  contamination: 0.1

retraining:
  schedule: '00:00'  # Daily at midnight

api_keys:
  fred: 'YOUR_FRED_API_KEY'
  news: 'YOUR_NEWS_API_KEY'

cache:
  directory: 'cache'
  expiry: 86400  # 24 hours in seconds

database:
  name: 'performance_metrics.db'